# Generated by Django 3.2.5 on 2021-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210731_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprofile',
            name='motto',
            field=models.TextField(blank=True),
        ),
    ]
