# Generated by Django 3.2.5 on 2021-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_travelprofile_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='accounts.TravelProfile'),
        ),
    ]
