# Generated by Django 3.2.5 on 2021-08-18 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_travelprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
