# Generated by Django 3.2.5 on 2021-08-03 07:38

import YouTravel.trips.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name_trip',
            field=models.CharField(max_length=15, validators=[YouTravel.trips.validators.is_title_start_alpha, YouTravel.trips.validators.is_title_start_capitalized, YouTravel.trips.validators.is_title_length_less]),
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='trip_images'),
        ),
    ]
