# Generated by Django 3.2.5 on 2021-08-18 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
